services:

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  pg:
    image: postgres:17
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  rabbit:
    image: rabbitmq:4.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
