[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
uvicorn = {extras = ["standard"], version = "^0.35.0"}
pydantic = {extras = ["email"], version = "^2.11.7"}
pydantic-settings = "^2.10.1"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.42"}
asyncpg = "^0.30.0"
alembic = "^1.16.4"
fastapi-users = {extras = ["sqlalchemy"], version = "^14.0.1"}
gunicorn = "^23.0.0"
aiohttp = "^3.12.15"
orjson = "^3.11.1"
jinja2 = "^3.1.6"
aiosmtplib = "^4.0.1"
sqladmin = {extras = ["full"], version = "^0.21.0"}
fastapi-cache2 = "^0.2.2"
redis = "^6.4.0"
faststream = {extras = ["cli", "rabbit"], version = "^0.6.2"}

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
