# Generated by Django 4.1.4 on 2023-01-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_rename_phone_numpber_card_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
