"""create model Product

Revision ID: 5072d8a428f3
Revises: 
Create Date: 2021-03-10 18:34:46.750318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5072d8a428f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
