"""add 'created_at' filed

Revision ID: 5a08f0c747ee
Revises: 5072d8a428f3
Create Date: 2021-03-10 18:48:41.244019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a08f0c747ee'
down_revision = '5072d8a428f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created_at')
    # ### end Alembic commands ###
