# Generated by Django 3.2 on 2022-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('kind', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
