# Generated by Django 4.2.5 on 2023-09-22 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="kind",
        ),
    ]
