# Generated by Django 3.2 on 2021-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='kind',
        ),
        migrations.AddField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='animalkind',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
