# Generated by Django 4.2.5 on 2023-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_remove_animal_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
