# Generated by Django 4.1.1 on 2022-09-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animalkind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='kind',
        ),
    ]
