# Generated by Django 3.2 on 2021-12-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_animalkind_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalfood',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
