# Generated by Django 4.0.5 on 2022-07-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_animalfood_options_animal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='animalkind',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
