"""remove bio from user

Revision ID: 3be210f62275
Revises: c25b4a0ef56d
Create Date: 2023-05-10 21:11:37.206996

"""
from alembic import op
import sqlalchemy as sa

# from models import Author, User

# revision identifiers, used by Alembic.
revision = "3be210f62275"
down_revision = "c25b4a0ef56d"
branch_labels = None
depends_on = None


metadata = sa.MetaData()

users_table = sa.Table(
    "blog_users",
    metadata,
    sa.Column("id", sa.Integer),
    sa.Column(
        "bio",
        sa.VARCHAR(),
    )
)

authors_table = sa.Table(
    "blog_authors",
    metadata,
    sa.Column("id", sa.Integer),
    sa.Column("user_id", sa.Integer),
    sa.Column(
        "bio",
        sa.VARCHAR(),
    )
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "bio")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column(
            "bio",
            sa.VARCHAR(),
            server_default="",
            nullable=False,
        ),
    )

    connection = op.get_bind()

    # connection.execute(
    #     sa.update(User)
    #     .values(
    #         bio=sa.select(Author.bio)
    #         .where(Author.user_id == User.id)
    #         .scalar_subquery(),
    #     )
    # )
    # connection.execute(
    #     sa.update(users_table)
    #     .values(
    #         bio=sa.select(authors_table.c.bio)
    #         .where(authors_table.c.user_id == users_table.c.id)
    #         .scalar_subquery(),
    #     )
    # )

    connection.execute(
        sa.update(users_table)
        .where(authors_table.c.user_id == users_table.c.id)
        .values({users_table.c.bio: authors_table.c.bio})
    )
    # ### end Alembic commands ###
