"""add field is_staff

Revision ID: aa596971d7ac
Revises: a4d5e8add247
Create Date: 2022-08-08 13:45:56.033483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aa596971d7ac"
down_revision = "a4d5e8add247"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_staff", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_staff")
    # ### end Alembic commands ###
