"""create posts-tags assoctiation table

Revision ID: cc281ab98083
Revises: 4cb26049bfb2
Create Date: 2022-02-05 11:22:02.833957

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cc281ab98083'
down_revision = '4cb26049bfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'posts_tags_association',
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ),
        sa.PrimaryKeyConstraint('post_id', 'tag_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_tags_association')
    # ### end Alembic commands ###
