"""add index to posts table

Revision ID: e8023afe2273
Revises: 7e82059a9d75
Create Date: 2022-02-02 21:05:14.185891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8023afe2273'
down_revision = '7e82059a9d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_blog_posts_author_id'),
        'blog_posts',
        ['author_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_posts_author_id'), table_name='blog_posts')
    # ### end Alembic commands ###
