"""upgrade users: add archived column

Revision ID: e9dbb556d516
Revises: 4fb730957be6
Create Date: 2023-05-10 20:29:43.211693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9dbb556d516"
down_revision = "4fb730957be6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column(
            "archived",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "archived")
    # ### end Alembic commands ###
