"""Added column bio to authors table

Revision ID: 2d6884d11e32
Revises: 04eb5a326a8e
Create Date: 2021-08-04 20:37:34.716460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6884d11e32'
down_revision = '04eb5a326a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sql = """
    ALTER TABLE blog_authors ADD COLUMN bio VARCHAR(300) DEFAULT '' NOT NULL;
    """
    op.add_column('blog_authors', sa.Column('bio', sa.String(length=300), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_authors', 'bio')
    # ### end Alembic commands ###
