"""create table users

Revision ID: 9a5fcb739c61
Revises: 
Create Date: 2022-10-28 22:51:16.900811

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9a5fcb739c61"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
