"""add column created_at to table users

Revision ID: e148fcae7e91
Revises: e69104ef0e3c
Create Date: 2022-04-29 20:37:55.409531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e148fcae7e91"
down_revision = "e69104ef0e3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
