"""add is_new column to products table

Revision ID: 76f6d570eff1
Revises: be427c651c14
Create Date: 2022-09-12 21:01:18.984116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76f6d570eff1"
down_revision = "be427c651c14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("is_new", sa.Boolean(), server_default="FALSE", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "is_new")
    # ### end Alembic commands ###
