"""add column created_at to products table

Revision ID: 22e8a31e1ad1
Revises: 075e6c768e39
Create Date: 2021-11-30 20:35:02.825421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e8a31e1ad1'
down_revision = '075e6c768e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'product',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created_at')
    # ### end Alembic commands ###
