"""add column updated_at to products table

Revision ID: ad9323dc0c0d
Revises: 410b0eafdff3
Create Date: 2021-11-30 20:57:58.511911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9323dc0c0d'
down_revision = '410b0eafdff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_at')
    # ### end Alembic commands ###
