CREATE TABLE users (
	id INTEGER NOT NULL,
	username VARCHAR(32) NOT NULL,
	email VARCHAR(100),
	is_staff BOOLEAN DEFAULT (0) NOT NULL,
	created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (username),
	UNIQUE (email)
);


CREATE TABLE posts (
	id INTEGER NOT NULL,
	title VARCHAR(100) NOT NULL,
	body TEXT DEFAULT '' NOT NULL,
	published_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	user_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id)
);
