# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\"%\n\x05Hello\x12\x0c\n\x04text\x18\x01 \x02(\t\x12\x0e\n\x06number\x18\x02 \x01(\x03\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\")\n\nHelloReply\x12\x1b\n\x05hello\x18\x01 \x02(\x0b\x32\x0c.hello.Hello2<\n\x07Greeter\x12\x31\n\x05Greet\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLO']._serialized_start=22
  _globals['_HELLO']._serialized_end=59
  _globals['_HELLOREQUEST']._serialized_start=61
  _globals['_HELLOREQUEST']._serialized_end=89
  _globals['_HELLOREPLY']._serialized_start=91
  _globals['_HELLOREPLY']._serialized_end=132
  _globals['_GREETER']._serialized_start=134
  _globals['_GREETER']._serialized_end=194
# @@protoc_insertion_point(module_scope)
