FROM python:3.11

WORKDIR /app

RUN pip install --upgrade pip "poetry==1.6.1"

COPY poetry.lock pyproject.toml ./

RUN poetry config virtualenvs.create false --local

RUN poetry install

COPY ./src/ ./

COPY ./build/entrypoint.sh ./

RUN chmod +x ./entrypoint.sh

CMD ["flask", "run"]
