# Generated by Django 5.0 on 2023-12-25 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0005_food"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"verbose_name_plural": "Food"},
        ),
    ]
