# Generated by Django 5.0 on 2023-12-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0006_alter_food_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="meals",
            field=models.ManyToManyField(related_name="animals", to="animals.food"),
        ),
    ]
