"""add is_new col to products

Revision ID: 05669b3d8670
Revises: 79631e851a8d
Create Date: 2022-06-07 21:01:05.761804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05669b3d8670'
down_revision = '79631e851a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_new', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_new')
    # ### end Alembic commands ###
