startproject:
	python -m django startproject zoo .

runserver:
	python manage.py runserver

startapp:
	python manage.py startapp <name>

makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

createsuperuser:
	python manage.py createsuperuser

runworker:
	celery -A zoo worker -l INFO
