image: python:3.12

stages:          # List of stages for jobs, and their order of execution
  - testing
  - build
  - deploy

#before_script:
#  - python --version
#  - python -m pip install --upgrade pip
#  - pip install poetry
#  - poetry install

lint:       # This job runs in the build stage, which runs first.
  stage: testing
  script:
    # - pylint $(git ls-files '*.py')
    - echo " Done ... "

test:   # This job runs in the test stage.
  stage: testing    # It only starts when the job in the build stage completes successfully.
  services:
    - postgres
  variables:
    POSTGRES_DB: shop
    POSTGRES_USER: user
    POSTGRES_PASSWORD: example
    SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:example@postgres:5432/shop"
  script:
    - python --version
    - python -m pip install --upgrade pip
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate
    - flask db upgrade
    - pytest

make-build:   # This job also runs in the test stage.
  stage: build    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Building ... Done ..."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application... Ok ..."
