image: python:3.12

stages:          # List of stages for jobs, and their order of execution
  - testing
  - build
  - deploy

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest-cov

lint:       # This job runs in the build stage, which runs first.
  stage: testing
  script:
    - pip install pylint
    # - pylint $(git ls-files '*.py')
    - echo "Lint works good ..."

test:   # This job runs in the test stage.
  stage: testing    # It only starts when the job in the build stage completes successfully.
  services:
    - postgres
  variables:
    DATABASE_URI: "postgresql+psycopg2://user:example@postgres:5432/blog"
    POSTGRES_DB: blog
    POSTGRES_USER: user
    POSTGRES_PASSWORD: example
  script:
    - flask db upgrade
    - pytest -s --cov --cov-report html --cov-fail-under 79

make-build:   # This job also runs in the test stage.
  stage: build    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Make build ..."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
