# Generated by Django 3.2 on 2023-10-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='b_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
