"""add token nullable field to users table

Revision ID: a972db2eb20b
Revises: fee2b2b229c1
Create Date: 2023-02-15 20:12:09.031742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a972db2eb20b"
down_revision = "fee2b2b229c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blog_users", sa.Column("token", sa.String(), nullable=True))
    op.create_unique_constraint("ix_users_token", "blog_users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ix_users_token", "blog_users", type_="unique")
    op.drop_column("blog_users", "token")
    # ### end Alembic commands ###
