"""add token not nullable field to users table

Revision ID: 2fb747db32ce
Revises: a972db2eb20b
Create Date: 2023-02-15 20:13:05.603873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from models.user import generate_token, User


# revision identifiers, used by Alembic.
revision = "2fb747db32ce"
down_revision = "a972db2eb20b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    session = Session(op.get_bind())
    users: list[User] = session.query(User).filter_by(token=None).all()
    for user in users:
        user.token = generate_token()

    session.commit()

    op.alter_column(
        "blog_users",
        "token",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blog_users",
        "token",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
