# Generated by Django 4.1.4 on 2022-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_alter_animal_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
