# Generated by Django 4.0.5 on 2022-06-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='kind',
        ),
    ]
