# Generated by Django 3.2 on 2022-12-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64, verbose_name='kind')),
                ('age', models.IntegerField(verbose_name='age')),
                ('desc', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
    ]
