[project]
name = "otus-django-2025-11"
version = "0.1.0"
description = ""
authors = [
    {name = "stanislav"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "django (>=6.0.4,<7.0.0)",
    "faker (>=40.15.0,<41.0.0)",
    "pillow (>=12.2.0,<13.0.0)",
    "bs4 (>=0.0.2,<0.0.3)",
    "celery[redis] (>=5.6.3,<6.0.0)",
    "django-celery-results (>=2.6.0,<3.0.0)",
    "django-celery-beat (>=2.9.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.3"
pytest-mock = "^3.15.1"
pytest-django = "^4.12.0"

