# Generated by Django 3.2.4 on 2021-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
