"""add column deleted

Revision ID: ab918bdbb5e5
Revises: bbd8f0c06d1b
Create Date: 2020-10-20 21:24:33.914765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab918bdbb5e5'
down_revision = 'bbd8f0c06d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted')
    # ### end Alembic commands ###
