"""add is_new column

Revision ID: bbd8f0c06d1b
Revises: 00faa80af24b
Create Date: 2020-10-20 21:08:01.323707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd8f0c06d1b'
down_revision = '00faa80af24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_new', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_new')
    # ### end Alembic commands ###
