# Generated by Django 3.2 on 2022-12-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='animal',
            new_name='animals',
        ),
    ]
