# Generated by Django 3.2 on 2021-12-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.TextField()),
                ('age', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'животное',
                'verbose_name_plural': 'животные',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AnimalKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
            ],
            options={
                'verbose_name': 'вид животного',
                'verbose_name_plural': 'виды животных',
                'ordering': ['name'],
            },
        ),
    ]
