# Generated by Django 4.1.1 on 2022-09-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='animals.animal'),
        ),
    ]
