# Generated by Django 5.0.6 on 2024-05-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
    ]
