# Generated by Django 4.1.4 on 2022-12-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_rename_animal_food_animals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.IntegerField(default=1, verbose_name="age"),
        ),
    ]
