"""add bio to users table

Revision ID: 18db0d1507e6
Revises: e5a9575a656c
Create Date: 2023-08-08 20:43:13.465989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18db0d1507e6"
down_revision: Union[str, None] = "e5a9575a656c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("bio", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bio")
    # ### end Alembic commands ###
