"""create tags table

Revision ID: 8605758fcfe8
Revises: bfb8d98c4f6f
Create Date: 2023-02-06 20:16:56.942894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8605758fcfe8"
down_revision = "bfb8d98c4f6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_tags")
    # ### end Alembic commands ###
