"""upgrade users: add created_at column

Revision ID: 3a8585c93e66
Revises: e9dbb556d516
Create Date: 2023-05-10 20:36:14.837680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a8585c93e66"
down_revision = "e9dbb556d516"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "created_at")
    # ### end Alembic commands ###
