"""create posts tags association table

Revision ID: 75394efe09f8
Revises: 34724cc25493
Create Date: 2023-05-15 20:41:50.341677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75394efe09f8"
down_revision = "34724cc25493"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_posts_tags_association",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["blog_posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["blog_tags.id"],
        ),
        sa.PrimaryKeyConstraint("post_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_posts_tags_association")
    # ### end Alembic commands ###
