"""add token to user

Revision ID: 9b6aa35b8bcb
Revises: fc4278713097
Create Date: 2023-08-18 20:21:08.536356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b6aa35b8bcb"
down_revision: Union[str, None] = "fc4278713097"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("token", sa.String(length=50), nullable=True),
    )
    op.create_unique_constraint(
        "ix_token_unique",
        "users",
        ["token"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ix_token_unique",
        "users",
        type_="unique",
    )
    op.drop_column("users", "token")
    # ### end Alembic commands ###
