"""user token new field

Revision ID: b24b3e59eff8
Revises: aeddea176ae8
Create Date: 2023-05-24 20:25:49.252998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import update

# revision identifiers, used by Alembic.
revision = "b24b3e59eff8"
down_revision = "aeddea176ae8"
branch_labels = None
depends_on = None


table_name_users = "blog_users"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        table_name_users,
        sa.Column("token", sa.String(), nullable=True),
    )
    bind = op.get_bind()

    metadata = sa.MetaData()
    metadata.reflect(bind=op.get_bind())

    users_table = metadata.tables[table_name_users]

    stmt = update(users_table).values(
        {
            users_table.c.token: sa.func.concat(
                sa.cast(
                    users_table.c.id,
                    sa.String,
                ),
                sa.cast(
                    users_table.c.created_at,
                    sa.String,
                ),
                sa.text("'qwerty'"),
            ),
        }
    )
    bind.execute(stmt)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name_users, "token")
    # ### end Alembic commands ###
