"""user token unique and not null

Revision ID: d6ba88513805
Revises: b24b3e59eff8
Create Date: 2023-05-24 20:40:57.946320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6ba88513805"
down_revision = "b24b3e59eff8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "blog_users",
        "token",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.create_unique_constraint(
        "user_token_unique_constraint",
        "blog_users",
        ["token"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_token_unique_constraint",
        "blog_users",
        type_="unique",
    )
    op.alter_column("blog_users", "token", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
