"""Create users table

Revision ID: 541d3abd047a
Revises: 3fb1dc39f239
Create Date: 2021-01-20 20:41:51.055639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541d3abd047a'
down_revision = '3fb1dc39f239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('is_staff', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
