# Generated by Django 4.2.5 on 2023-09-22 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Animal",
        ),
    ]
