# Generated by Django 5.0 on 2023-12-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0004_alter_animal_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
            ],
        ),
    ]
