# Generated by Django 5.1 on 2024-08-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0008_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
