image: python:3.12

stages:          # List of stages for jobs, and their order of execution
  - testing
  - build
  - deploy

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install poetry
  - poetry install
  - source `poetry env info --path`/bin/activate

lint:       # This job runs in the build stage, which runs first.
  stage: testing
  script:
    - pylint $(git ls-files '*.py')

test:   # This job runs in the test stage.
  stage: testing    # It only starts when the job in the build stage completes successfully.
  services:
    - postgres
  variables:
    POSTGRES_USER: gitlabuser
    POSTGRES_PASSWORD: gitlabsercrepas222d
    POSTGRES_DB: gldb
    POSTGRES_HOST: postgres
    COVERAGE_DIR: "coverage-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  script:
    - pytest -s --cov --cov-report html:$COVERAGE_DIR --cov-fail-under 88
  artifacts:
    name: $COVERAGE_DIR
    paths:
      - $COVERAGE_DIR
    when: on_success
    expire_in: 1 week

#make-build:   # This job also runs in the test stage.
#  stage: build    # It can run at the same time as unit-test-job (in parallel).
#  script:
#    - echo "Building ..."
#
#deploy-job:      # This job runs in the deploy stage.
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  script:
#    - echo "Deploying application..."
