services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d blog -U user" ]
      interval: 5s
      timeout: 3s
      retries: 6

  app:
    image: danteonline/python-base-2024-07
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@pg:5432/blog"
      SQLALCHEMY_ASYNC_DATABASE_URI: "postgresql+asyncpg://user:password@pg:5432/blog"
    depends_on:
      pg:
        condition: service_healthy
    command: bash -c "
      source `poetry env info --path`/bin/activate
      && alembic upgrade head
      && python main.py
      "


#  adminer:
#    image: adminer
#    ports:
#      - "8080:8080"
#
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "5050:80"
