services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d shop -U user" ]
      interval: 5s
      timeout: 3s
      retries: 5

#  adminer:
#    image: adminer
#    ports:
#      - "8080:8080"

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "5050:80"

  app:
    image: danteonline/python-basic-2024-05
    build:
      dockerfile: ./Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:example@pg:5432/shop"
    #    network_mode: host
    #    entrypoint:
    #      - bash
    #      - "entrypoint.sh"
    #    command:
    #      - flask
    #      - run
    ports:
      - "8080:80"
    depends_on:
      pg:
        condition: service_healthy

#volumes:
#  pgdata:
