services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
#    volumes:
#      - db-data:/var/lib/postgresql/data
    # restart: always
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d blog -U user" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: danteonline/base-python-2024-03
    environment:
      DATABASE_URI: "postgresql+psycopg2://user:example@pg:5432/blog"
    ports:
      - "8000:80"
    depends_on:
      pg:
        condition: service_healthy

#volumes:
#  db-data:
