# Generated by Django 4.1.7 on 2023-03-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_age',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
