# Generated by Django 5.0 on 2023-12-25 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_animal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
