[project]
name = "2026-05"
version = "0.1.0"
description = ""
authors = [
    {name = "Stanislav",email = "stanislav3@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.lint.dependencies]
ruff = "^0.16.0"
pylint = "^4.0.6"
flake8 = "^7.3.0"
black = "^26.5.1"
isort = "^8.0.1"


[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py312"

line-length = 120

extend-exclude = ["data"]

select = [
    "E4"
]

ignore = [
    "E501",
]