[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
alembic = "^1.13.3"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
asyncpg = "^0.30.0"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
