"""add created_at to users table

Revision ID: eba7dfb0e6e2
Revises: 2b7c7066c01f
Create Date: 2023-02-01 20:26:14.508690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session



# revision identifiers, used by Alembic.
revision = "eba7dfb0e6e2"
down_revision = "2b7c7066c01f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "created_at")
    # ### end Alembic commands ###
