"""add token column to user table

Revision ID: 40dd9f95bb0f
Revises: 53809d836638
Create Date: 2022-11-18 20:11:50.549556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40dd9f95bb0f"
down_revision = "53809d836638"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("token", sa.String(length=64), nullable=True)
    )
    op.alter_column(
        "users", "archived", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.create_unique_constraint(None, "users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "archived", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("users", "token")
    # ### end Alembic commands ###
