"""add created_at

Revision ID: 442d63521bd5
Revises: f482c3debcca
Create Date: 2022-10-28 23:00:50.126952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "442d63521bd5"
down_revision = "f482c3debcca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
