"""create Tag model

Revision ID: 4cb26049bfb2
Revises: e8023afe2273
Create Date: 2022-02-05 11:11:02.842988

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4cb26049bfb2'
down_revision = 'e8023afe2273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blog_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_tags')
    # ### end Alembic commands ###
