"""add token column to users table

Revision ID: 6de62bb81da2
Revises: 1d11923da850
Create Date: 2022-05-24 20:17:05.315077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6de62bb81da2"
down_revision = "1d11923da850"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token")
    # ### end Alembic commands ###
