# Generated by Django 4.0.5 on 2022-06-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animalkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='animals.animalkind'),
        ),
    ]
