# Generated by Django 5.1 on 2024-08-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("pk",), "verbose_name_plural": "Categories"},
        ),
    ]
