# Generated by Django 4.2.2 on 2023-06-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payed_at", models.DateTimeField(blank=True, null=True)),
                ("card_ends_with", models.CharField(blank=True, max_length=5)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Confirmed")], default=0
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.order"
                    ),
                ),
            ],
        ),
    ]
