# Generated by Django 4.2.2 on 2023-06-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_orderpaymentdetails"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderpaymentdetails",
            options={"verbose_name_plural": "Order Payment Details"},
        ),
        migrations.AlterField(
            model_name="orderpaymentdetails",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_details",
                to="shop.order",
            ),
        ),
    ]
