"""Added articles-tags association table

Revision ID: 68a7cf178c25
Revises: 6f9cae946e8d
Create Date: 2021-08-07 12:32:18.487866

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '68a7cf178c25'
down_revision = '6f9cae946e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blog_articles_tags_association_table',
        sa.Column('article_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['article_id'], ['blog_articles.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['blog_tags.id'], ),
        sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_articles_tags_association_table')
    # ### end Alembic commands ###
