"""Added create_at field to users table

Revision ID: bd69b7386d03
Revises: db717d3bc766
Create Date: 2021-10-26 20:47:40.750638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd69b7386d03'
down_revision = 'db717d3bc766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_app__users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_app__users', 'created_at')
    # ### end Alembic commands ###
