"""create author_bio table

Revision ID: 37592d69b1f9
Revises: cdfb38af8945
Create Date: 2023-02-01 20:52:48.275496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37592d69b1f9"
down_revision = "cdfb38af8945"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog_authorbios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), server_default="", nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["blog_authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("author_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_authorbios")
    # ### end Alembic commands ###
