"""add full_name col to users table

Revision ID: 02f4713e6e37
Revises: 0a665288abf8
Create Date: 2024-02-02 20:57:52.119419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02f4713e6e37"
down_revision: Union[str, None] = "0a665288abf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name",
            sa.String(length=100),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_users_full_name"),
        "users",
        ["full_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_full_name"), table_name="users")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
