"""add bio to author

Revision ID: c25b4a0ef56d
Revises: c0856bbe4253
Create Date: 2023-05-10 21:02:53.648629

"""
from alembic import op
import sqlalchemy as sa

from models import Author, User


# revision identifiers, used by Alembic.
revision = "c25b4a0ef56d"
down_revision = "c0856bbe4253"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_authors",
        sa.Column("bio", sa.String(), server_default="", nullable=False),
    )
    connection = op.get_bind()

    connection.execute(
        sa.update(Author)
        .where(Author.user_id == User.id)
        .values({Author.bio: User.bio})
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_authors", "bio")
    # ### end Alembic commands ###
