"""create manager table

Revision ID: e18f05b320b7
Revises: abff2a8f2a18
Create Date: 2022-10-28 23:23:29.661084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e18f05b320b7"
down_revision = "abff2a8f2a18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("managers")
    # ### end Alembic commands ###
