"""add column is_staff to table users

Revision ID: e69104ef0e3c
Revises: 9c96f9590851
Create Date: 2022-04-29 20:25:55.270652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e69104ef0e3c"
down_revision = "9c96f9590851"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_staff", sa.Boolean(), server_default="FALSE", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_staff")
    # ### end Alembic commands ###
