# Generated by Django 4.1.1 on 2022-09-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Animal food',
            },
        ),
    ]
