"""Create product table

Revision ID: 364b32984914
Revises: 
Create Date: 2023-12-06 20:29:32.070550

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "364b32984914"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
