"""drop posts tags association table

Revision ID: e3b2d698ca83
Revises: 90a498113347
Create Date: 2025-05-19 21:05:34.535266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3b2d698ca83"
down_revision: Union[str, None] = "90a498113347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts_tags_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts_tags_association",
        sa.Column(
            "post_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "tag_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name="fk_posts_tags_association_post_id_posts",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name="fk_posts_tags_association_tag_id_tags",
        ),
        sa.PrimaryKeyConstraint(
            "post_id", "tag_id", name="pk_posts_tags_association"
        ),
    )
    # ### end Alembic commands ###
