# Generated by Django 3.2 on 2022-03-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='kind',
        ),
    ]
