services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      DATABASE_URI: "postgresql+psycopg://user:example@localhost:5432/blog"
      FLASK_APP: main.py
      PYTHONPATH: ./
#    command:
#      - flask
#      - db
#      - upgrade
#    ports:
#      - "5000:80"
    network_mode: host

volumes:
  db-data:
