"""Initial migration.

Revision ID: 167cfdf4d23b
Revises: 
Create Date: 2022-06-07 20:30:22.608846

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '167cfdf4d23b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
