"""downgrade product name length

Revision ID: 79631e851a8d
Revises: 167cfdf4d23b
Create Date: 2022-06-07 20:34:37.673612

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '79631e851a8d'
down_revision = '167cfdf4d23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'product', 'name',
        existing_type=sa.VARCHAR(length=120),
        type_=sa.String(length=100),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'product', 'name',
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False)
    # ### end Alembic commands ###
