# Generated by Django 4.1.4 on 2022-12-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='phone_numpber',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
