# Generated by Django 4.1.4 on 2022-12-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_card_phone_numpber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='phone_numpber',
            new_name='phone_number',
        ),
    ]
