# Generated by Django 5.1 on 2024-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0005_order_orderproduct_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="promocode",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
