# Generated by Django 4.2 on 2023-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="device_name",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="card",
            name="device_type",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
