"""add full_name col to users table

Revision ID: 5b37e4b88c86
Revises: f63291c5efab
Create Date: 2023-11-08 20:59:21.655197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b37e4b88c86"
down_revision: Union[str, None] = "f63291c5efab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name",
            sa.String(100),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
