"""add unique index to posts table

Revision ID: d43c2b46e4e1
Revises: bf6af59287fe
Create Date: 2023-11-08 21:06:42.812461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d43c2b46e4e1"
down_revision: Union[str, None] = "bf6af59287fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "ix_posts_title_published_at",
        "posts",
        ["title", "published_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ix_posts_title_published_at",
        "posts",
        type_="unique",
    )
    # ### end Alembic commands ###
