"""Create users table

Revision ID: 2758258ebef6
Revises: 
Create Date: 2022-02-02 20:38:03.586687

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2758258ebef6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blog_users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('username', sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_users')
    # ### end Alembic commands ###
