"""add email to users table

Revision ID: 6d5b046467a8
Revises: abd9048193a4
Create Date: 2023-08-04 20:36:46.969409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d5b046467a8"
down_revision: Union[str, None] = "abd9048193a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.String(length=100), nullable=True),
    )
    op.create_unique_constraint("users_unique_email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_unique_email", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
