"""add token field to users table

Revision ID: 7a20747bd0de
Revises: 5f2e40236aee
Create Date: 2022-08-22 20:29:46.533757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a20747bd0de"
down_revision = "5f2e40236aee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(), nullable=True))
    op.create_unique_constraint("users_token_key", "users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_token_key", "users", type_="unique")
    op.drop_column("users", "token")
    # ### end Alembic commands ###
