"""create table authors

Revision ID: 983300176ac2
Revises: 5dfb3d71b6a7
Create Date: 2022-08-22 20:18:43.796873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "983300176ac2"
down_revision = "5dfb3d71b6a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authors")
    # ### end Alembic commands ###
