"""Added access_token column to User model

Revision ID: 987081ed9e4e
Revises: bbc42d8c4ab5
Create Date: 2021-11-16 20:32:38.064492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987081ed9e4e'
down_revision = 'bbc42d8c4ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_app__users',
                  sa.Column('access_token',
                            sa.String(length=36),
                            nullable=True))
    op.create_index(op.f('ix_blog_app__users_access_token'),
                    'blog_app__users',
                    ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_app__users_access_token'), table_name='blog_app__users')
    op.drop_column('blog_app__users', 'access_token')
    # ### end Alembic commands ###
