"""user bio

Revision ID: aeddea176ae8
Revises: 75394efe09f8
Create Date: 2023-05-22 20:20:22.687788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aeddea176ae8"
down_revision = "75394efe09f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column("bio", sa.String(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "bio")
    # ### end Alembic commands ###
