"""Added posts tags association table

Revision ID: bbc42d8c4ab5
Revises: e3410ee446fc
Create Date: 2021-10-26 20:59:34.049185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc42d8c4ab5'
down_revision = 'e3410ee446fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_app__posts_tags_association_table',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_app__posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_app__tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_app__posts_tags_association_table')
    # ### end Alembic commands ###
