# Generated by Django 5.2 on 2025-04-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
