# Generated by Django 5.2 on 2025-04-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ("id",)},
        ),
    ]
