# Generated by Django 5.2 on 2025-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeRating",
            fields=[
                (
                    "name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
