# Generated by Django 5.2 on 2025-04-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_agerating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="age_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="movies.agerating",
            ),
        ),
    ]
