# Generated by Django 5.2 on 2025-04-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_age_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="age_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movies",
                to="movies.agerating",
            ),
        ),
    ]
