# Generated by Django 5.2 on 2025-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movie_age_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
