# Generated by Django 5.2 on 2025-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="movies",
                to="movies.genre",
            ),
        ),
    ]
