# Generated by Django 4.0.5 on 2022-07-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_userdemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('userdemo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myauth.userdemo')),
                ('internal_id', models.PositiveSmallIntegerField()),
                ('internal_email', models.EmailField(max_length=254)),
            ],
            bases=('myauth.userdemo',),
        ),
    ]
