[tool.poetry]
name = "sales-shop"
version = "0.1.0"
description = ""
authors = ["Suren Khorenyan <surenkhorenyan@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.2.2"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.1.0"
