# Generated by Django 5.0 on 2024-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_category_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
