"""create publication_tag_association table

Revision ID: ca484f98ca3a
Revises: a04a4cbc68bb
Create Date: 2025-01-22 21:08:34.135323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca484f98ca3a"
down_revision: Union[str, None] = "a04a4cbc68bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publication_tag_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publication.id"],
            name=op.f(
                "fk_publication_tag_association_publication_id_publication"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
            name=op.f("fk_publication_tag_association_tag_id_tag"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_publication_tag_association")
        ),
        sa.UniqueConstraint(
            "publication_id",
            "tag_id",
            name=op.f(
                "uq_publication_tag_association_publication_id"
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_tag_association")
    # ### end Alembic commands ###
