[project]
name = "blog-app-2025-11"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "psycopg[binary]>=3.3.3",
    "sqlalchemy>=2.0.48",
]

[dependency-groups]
dev = [
    "black>=26.3.1",
    "mypy>=1.19.1",
]
