"""add created_at to posts-tags association

Revision ID: 9734023a772a
Revises: 7e5f52395b00
Create Date: 2024-02-06 20:53:19.720737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9734023a772a"
down_revision: Union[str, None] = "7e5f52395b00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts_tags_association",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "posts_tags_association",
        "created_at",
    )
    # ### end Alembic commands ###
