version: "3.9"

services:

  shop-prod:
    image: danteonline/ci-cd-gitlab-2022-08:latest
    build:
      context: .
      dockerfile: ./docker-build/shop-prod/Dockerfile
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demouser -d blog"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
