SYNC_ENGINE = "psycopg2"
# SYNC_ENGINE = "pg8000"
ASYNC_ENGINE = "asyncpg"
SQLALCHEMY_DB_URI = f"postgresql+{SYNC_ENGINE}://username:passwd!@localhost:5432/blog"
SQLALCHEMY_ASYNC_DB_URI = SQLALCHEMY_DB_URI.replace(SYNC_ENGINE, ASYNC_ENGINE)
SQLALCHEMY_ECHO = False
SQLALCHEMY_POOL_SIZE = 50
SQLALCHEMY_POOL_MAX_OVERFLOW = 10
