version: "3.9"

services:
  shop-prod:
    image: danteonline/base-python-2022-05:latest
    build:
      context: .
      dockerfile: ./docker-build/shop-prod/Dockerfile
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "passwd!"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d shop"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:

