# Generated by Django 4.1.1 on 2022-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
