# Generated by Django 3.2 on 2022-03-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20220319_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animalkind'),
        ),
    ]
