# Generated by Django 3.2 on 2022-03-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalkind',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
