# Generated by Django 3.2 on 2021-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animalfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalkind',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
