# Generated by Django 4.1.1 on 2022-09-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_animal_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='animals.animalkind'),
            preserve_default=False,
        ),
    ]
