# Generated by Django 4.1.1 on 2022-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animalfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='food',
            field=models.ManyToManyField(related_name='animals', to='animals.animalfood'),
        ),
    ]
